name: Profile 3d grass and snake

on:
  schedule:
    - cron: "0 */6 * * *"      # 6시간마다 (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGIN: najung-h

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) 계정 전체 커밋(지난 6시간) 집계: REST Search
      #    - private 포함하려면 METRICS_TOKEN = 개인 PAT (repo 권한 포함) 이어야 함
      - name: Check account-wide commits in last 6 hours
        id: acc_check
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          FROM=$(date -u -d '6 hours ago' +%Y-%m-%dT%H:%M:%SZ)
          Q="author:${LOGIN} committer-date:>=${FROM}"
          echo "Search query: $Q"
          COUNT=$(gh api -H "Accept: application/vnd.github+json" /search/commits -f q="$Q" --jq '.total_count')
          echo "commit_count=$COUNT" | tee -a "$GITHUB_OUTPUT"

      - name: No recent commits across account, skip the run
        if: ${{ steps.acc_check.outputs.commit_count == '0' }}
        run: |
          echo "No commits in the last 6 hours across the account. Exit."
          exit 0

      - name: Prepare dist folder
        run: mkdir -p dist

      - name: Generate 3d grass
        uses: lowlighter/metrics@latest
        with:
          user: najung-h
          token: ${{ secrets.METRICS_TOKEN }}   # 개인 PAT (repo 권장)
          template: classic
          filename: dist/metrics-6m.svg
          base: ""
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # 캐시 영향 최소화
          use_cache: no

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: najung-h
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # ✅ 산출물이 동일해도 항상 diff 발생하도록 스탬프 추가
      - name: Write stamp file (forces change)
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > dist/.stamp.txt
          echo "commit_count=${{ steps.acc_check.outputs.commit_count }}" >> dist/.stamp.txt

      # 디버그: 변경 확인
      - name: Show git diff summary
        run: |
          git status
          git diff --stat || true
          ls -alh dist

      # output 브랜치 배포
      - name: Deploy profile assets to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update profile assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 기본 브랜치에도 동기화
      - name: Commit dist to default branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync dist assets to default branch"
          branch: master
          file_pattern: |
            dist/**
