name: Profile 3d grass and snake

on:
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다 - grass
    - cron: "0 */6 * * *"   # (UTC) 6시간마다 실행
  workflow_dispatch:         # 수동 실행

# output 브랜치로 푸시하려면 repo 컨텐츠 쓰기 권한이 필요
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 저장소 체크아웃
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1-1) dist 폴더 미리 생성 (중요!)
      - name: Prepare dist folder
        run: mkdir -p dist

      # 2) 입체 잔디 생성
      - name: Generate 3d grass
        uses: lowlighter/metrics@latest
        with:
          user: najung-h
          token: ${{ secrets.METRICS_TOKEN }}  # PAT 필요
          template: classic
          filename: dist/metrics-6m.svg   # dist 폴더에 저장
          base: ""
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # 3) 뱀 생성 
      - name: Generate snake grass
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: najung-h
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      - run git status

      # (선택) 생성물 확인용
      - name: List dist
        run: ls -alh dist || true

      # (선택) 기본 브랜치로 커밋/푸시가 필요할 때만 사용
      #  - 기본 브랜치가 main이라면 branch 값을 main으로 변경
      #  - 불필요하면 이 스텝 통째로 삭제
      - name: Push changes to default branch
        if: ${{ false }} # 필요하면 true로 바꾸거나 이 줄 삭제
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true


      # 4) dist/ 를 output 브랜치로 배포
      - name: Deploy profile to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update profile assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}