name: Metrics (6 months contributions)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug token: whoami
        env:
          TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          set -e
          echo "Checking PAT (classic) with read:user, public_repo ..."
          RESP=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/user)
          echo "$RESP" | grep -q '"login"' || (echo "❌ Token invalid (no login in response)"; echo "$RESP"; exit 1)
          echo "✅ Token OK. login:" $(echo "$RESP" | sed -n 's/.*"login": *"\([^"]*\)".*/\1/p')

      - name: Generate metrics (6 months)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # 반드시 classic PAT
          user: najung-h
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          filename: metrics-6m.svg
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics-6m.svg"
