name: Metrics (6 months contributions)

on:
  schedule:
    - cron: "0 0 * * *"      # 매일 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics (6 months)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}      # PAT(클래식) 필수
          user: najung-h
          template: classic
          filename: metrics-6m.svg
          base: ""
          config_timezone: Asia/Seoul

          # 6개월 잔디
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ⬇️ main/master 대신 별도 브랜치에 커밋
          committer_branch: metrics
          committer_message: "chore: update metrics (6 months)"
