name: Metrics (6 months contributions)

on:
  schedule:
    - cron: "0 0 * * *"      # 매일 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # 필수: 본인 계정
          user: najung-h
          # 여기! 방금 만든 PAT 전달
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          filename: metrics-6m.svg
          base: ""
          config_timezone: Asia/Seoul

          # 6개월 잔디
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Commit and push metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics-6m.svg
          git commit -m "Update metrics (6 months)" || echo "No changes"
          git push
