name: Metrics smoke

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke: render header only
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ← PAT 대신 내장 토큰
          user: najung-h
          template: classic
          base: "header"                      # ← 가장 가벼운 출력
          filename: metrics-smoke.svg
          output_action: commit
          committer_branch: master            # 기본 브랜치명 맞추기
          committer_message: "chore: add metrics-smoke.svg"
