name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # (UTC) 6시간마다 실행
  workflow_dispatch:         # 수동 실행

# output 브랜치로 푸시하려면 repo 컨텐츠 쓰기 권한이 필요
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - name: Checkout repo
        uses: actions/checkout@v4

      # Snake 애니메이션 생성 (SVG/Dark/GIF -> dist/)
      - name: Generate snake SVG/GIF
        uses: Platane/snk@v3
        with:
          github_user_name: najung-h
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
            github-contribution-grid-snake.gif


      # (선택) 기본 브랜치로 커밋/푸시가 필요할 때만 사용
      #  - 기본 브랜치가 main이라면 branch 값을 main으로 변경
      #  - 불필요하면 이 스텝 통째로 삭제
      - name: Push changes to default branch
        if: ${{ false }} # 필요하면 true로 바꾸거나 이 줄 삭제
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true


